### ISSUE TITLE
proxyproto: proxy protocol signature not present

### ISSUE THREAD

**Issue by Mr-Sheep** [ColetteContreras/v2ray-poseidon#104]
使用Docker配置V2Ray-Poseidon，報錯
```
v2ray-ws-tls    | 2021/04/03 00:04:29 http: TLS handshake error from :49185: proxyproto: proxy protocol signature not present
```
Server和Client均嘗試配置`Allow Insecure`，無效

`config.json`內容如下
```
{
  "poseidon": {
    "panel": "v2board",     
    "nodeId": 76,                
    "checkRate": 60,            
    "webapi": "https://abc.com",
    "token": "131",   
    "speedLimit": 0, 
    "user": {
      "maxOnlineIPCount": 0,  
      "speedLimit": 0        
    },
    "acceptProxyProtocol": true
  }
}
```
`docker-compose.yml`內容如下
```
version: '3'

services:
  v2ray-ws-tls:
    image: v2cc/poseidon
    container_name: v2ray-ws-tls
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config.json:/etc/v2ray/config.json
    environment:
      - CERT_MODE=http
      - CERT_DOMAIN=abc.com
    logging:
      driver: "json-file"
      options:
        max-size: 2g
```
