### ISSUE TITLE
运行后提示获取配置错误EOF

### ISSUE THREAD

**Issue by AreCie** [ColetteContreras/v2ray-poseidon#107]
### 日志
```v2ray-ws    | v2ray -config /etc/v2ray/config.json
v2ray-ws    | V2Ray-Poseidon v2.2.0 (Xray-core: 1.4.2)
v2ray-ws    | env[CERT_FILE]=
v2ray-ws    | env[KEY_FILE]=
v2ray-ws    | env[CERT_MODE]=
v2ray-ws    | 2021/08/14 05:13:38 [Info] V2ray-Poseidon: updating geoip.dat and geosite.dat
v2ray-ws    | 2021/08/14 05:13:39 [Warning] V2ray-Poseidon: panel: V2board
v2ray-ws    | 2021/08/14 05:13:39 [Warning] V2ray-Poseidon: node > check interval 60s
v2ray-ws    | 2021/08/14 05:13:39 [Warning] V2ray-Poseidon: node > speed limit unlimited
v2ray-ws    | 2021/08/14 05:13:39 [Warning] V2ray-Poseidon: user > max online ip count 0
v2ray-ws    | 2021/08/14 05:13:39 [Warning] V2ray-Poseidon: user > speed limit unlimited
v2ray-ws    | 2021/08/14 05:13:40 [Error] V2ray-Poseidon: fetch v2ray config error: http get > Get "https://v2.arecie.com/api/v1/server/poseidon/config?local_port=39817&node_id=1&poseidon_version=v2.2.0&token=2042642971%40qq.com": EOF
v2ray-ws    | 2021/08/14 05:14:39 [Error] V2ray-Poseidon: fetch v2ray config error: http get > Get "https://v2.arecie.com/api/v1/server/poseidon/config?local_port=39817&node_id=1&poseidon_version=v2.2.0&token=2042642971%40qq.com": EOF
v2ray-ws    | 2021/08/14 05:15:39 [Error] V2ray-Poseidon: fetch v2ray config error: http get > Get "https://v2.arecie.com/api/v1/server/poseidon/config?local_port=39817&node_id=1&poseidon_version=v2.2.0&token=2042642971%40qq.com": EOF
```
### `config.json`配置文件
```
{
  "poseidon": {
    "panel": "v2board",         // 这一行必须存在，且不能更改
    "nodeId": 1,                // 你的节点 ID 和 v2board 里的一致
    "checkRate": 60,            // 每隔多长时间同步一次配置文件、用户、上报服务器信息
    "webapi": "https://v2.arecie.com",// v2board 的域名信息
    "token": "2042642971@qq.com",   // v2board 和 v2ray-poseidon 的通信密钥

    "speedLimit": 0, // 节点限速 单位 字节/s 0 表示不限速
    "user": {
      "maxOnlineIPCount": 0,  // 用户同时在线 IP 数限制 0 表示不限制
      "speedLimit": 0         // 用户限速 单位 字节/s 0 表示不限速
    },
    // 是否通过 HAProxy 代理协议，获取用户的真实 IP
    "acceptProxyProtocol": false
  }
}
```
### `docker-compose.yml`配置文件
```
version: '3'

services:
  v2ray-ws-tls:
    image: v2cc/poseidon
    container_name: v2ray-ws-tls
    restart: always
    ports:
      - "443:443"
      #- "80:80"
    volumes:
      - ./config.json:/etc/v2ray/config.json
      #- ./v2ray.crt:/etc/v2ray/v2ray.crt
      #- ./v2ray.key:/etc/v2ray/v2ray.key
    environment:
      # 手动指定证书文件，配置文件需要映射到容器里面
      #- CERT_FILE=/etc/v2ray/v2ray.crt
      #- KEY_FILE=/etc/v2ray/v2ray.key

      # 让程序自动生成 TLS 证书，支持 http 和 dns 两种方式
      # 若使用 http 方式获取证书，需要将 80 端口映射到主机并放行
      - CERT_MODE=dns
      # dns_cf 或 dns_namesilo 或 dns_namecheap
      - DNS_PROVIDER=dns_cf
      # 申请 DNS 证书的域名
      - CERT_DOMAIN=n1.gkd.ee
      # 使用 cloudflare DNS 验证
      - CF_Email=2042642971@qq.com
      - CF_Key=1280048a7f7f0ff73009aff5df1ff900a069e
      # 使用 namesilo DNS 验证
      - Namesilo_Key=
      # 使用 namecheap DNS 验证
      - NAMECHEAP_USERNAME=
      - NAMECHEAP_API_KEY=
    logging:
      driver: "json-file"
      options:
        max-size: 2g

```
### 前台节点配置
![image](https://user-images.githubusercontent.com/41849402/129420873-18d0e812-883a-4fff-b8e0-c30c3fc260d3.png)
